services:
  gateway:
    image: huynhducphu2502/vnft-gateway:latest
    ports:
      - "3000:80"
    restart: unless-stopped

  hrm:
    image: huynhducphu2502/vnft-hrm:latest
    ports:
      - "3001:80"
    restart: unless-stopped

  crm:
    image: huynhducphu2502/vnft-crm:latest
    ports:
      - "3002:80"
    restart: unless-stopped
