import type { Gender } from './UserSessionResponse';
import type { MaritalStatus } from './UpdateCurrentUserProfileRequest';
import type { BankInformationResponse } from './BankInformation/BankInformationResponse';
import type { DependentResponse } from './Dependent/DependentResponse';
import type { EducationRecordResponse } from './EducationRecord/EducationRecordResponse';
import type { WorkExperienceResponse } from './WorkExperience/WorkExperienceResponse';

export interface UserProfileResponse {
  id: string;
  username: string;
  fullName?: string;
  englishName?: string;
  employeeCode?: string;
  attendanceCode?: string;
  checkInTime?: string;
  checkOutTime?: string;
  departmentId?: string;
  departmentName?: string;
  groupId?: string;
  groupName?: string;
  positionId?: string;
  positionName?: string;
  roleId?: string;
  roleName?: string;
  phoneNumber?: string;
  avatarKey?: string;
  avatarUrl?: string;
  gender?: Gender;
  dateOfBirth?: string;
  maritalStatus?: MaritalStatus;
  placeOfBirth?: string;
  placeOfOrigin?: string;
  nationality?: string;
  religion?: string;
  ethnicity?: string;
  permanentAddress?: string;
  permanentCity?: string;
  currentAddress?: string;
  currentCity?: string;
  citizenIdNumber?: string;
  citizenIdIssueDate?: string;
  citizenIdIssuePlace?: string;
  citizenIdFrontImageKey?: string;
  citizenIdFrontImageUrl?: string;
  citizenIdBackImageKey?: string;
  citizenIdBackImageUrl?: string;
  bankInformations?: BankInformationResponse[];
  dependents?: DependentResponse[];
  educationRecords?: EducationRecordResponse[];
  workExperiences?: WorkExperienceResponse[];
  active?: boolean;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
}

