/**
 * System Permission Constants
 * Defined here for centralized access and maintainability.
 * Synchronized with the backend's initialization seed metadata.
 */
export const PERMISSIONS = {
  // Hồ sơ cá nhân
  PROFILE_VIEW_SELF: "PROFILE_VIEW_SELF",
  PROFILE_UPDATE_SELF: "PROFILE_UPDATE_SELF",

  // Chấm công
  ATTENDANCE_VIEW_SELF: "ATTENDANCE_VIEW_SELF",
  ATTENDANCE_MANAGE: "ATTENDANCE_MANAGE",

  // Bảng lương
  PAYROLL_MANAGE: "PAYROLL_MANAGE",

  // Profit Report
  PROFIT_REPORT_MANAGE: "PROFIT_REPORT_MANAGE",

  // Đơn từ
  REQUEST_FORM_VIEW_SELF: "REQUEST_FORM_VIEW_SELF",
  REQUEST_FORM_CREATE_SELF: "REQUEST_FORM_CREATE_SELF",
  REQUEST_FORM_CANCEL_SELF: "REQUEST_FORM_CANCEL_SELF",
  REQUEST_FORM_APPROVE_DEPARTMENT: "REQUEST_FORM_APPROVE_DEPARTMENT",
  REQUEST_FORM_APPROVE_ALL: "REQUEST_FORM_APPROVE_ALL",

  // Đánh giá hiệu suất
  PERFORMANCE_REVIEW_DEPARTMENT: "PERFORMANCE_REVIEW_DEPARTMENT",
  PERFORMANCE_REVIEW_ALL: "PERFORMANCE_REVIEW_ALL",

  // Báo cáo
  ALLOWANCE_REPORT_VIEW: "ALLOWANCE_REPORT_VIEW",

  // Nhân sự & Danh mục & Hệ thống (Quản trị)
  USER_MANAGE: "USER_MANAGE",
  MASTER_DATA_MANAGE: "MASTER_DATA_MANAGE",
  SETTINGS_MANAGE: "SETTINGS_MANAGE",
} as const;
